export default [
    {
        name: "this shouldn't show if i clicked on 40s or 30s",
        decade: 50,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "this shouldn't show if i clicked on 30s or 50s",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "this shouldn't show if i clicked on 40s or 50s",
        decade: 30,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "Pinocchio",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "Fantasia",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "Dumbo",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "Bambi",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "Miracle on 34th Street",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "Cat People",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
    {
        name: "Citizen Kane",
        decade: 40,
        // media: require('../assets/dataImages/'),
        mediaType: "image",
        desc: "",
        swiped: false,
        answer: "answer",
    },
]